apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: mp
  name: mongodb
  namespace: user1-tenant
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/instance: mongodb
status:
  loadBalancer: {}
